version: '3'

services:
  postgres:
    image: postgres
    container_name: "murcydb"
    ports:
      - "5432:5432"
    env_file:
      - enviroment.env
  murcy_api:
    build: 
      context: ./BackEnd
      dockerfile: Dockerfile
    container_name: murcyapi
    ports:
      - "9090:8080"
    env_file:
      - enviroment.env
    depends_on:
      - postgres
  murcy_app:
    build: 
      context: ./FrontEndOld
      dockerfile: Dockerfile
    container_name: murcy_application
    ports:
      - "80:80"