version: '3'

services:
  postgres:
    image: postgres
    container_name: "murcydb"
    volumes:
      - ./postgres_db_init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    env_file:
      - enviroment.env
  murcy_api_old:
    build: 
      context: ./BackEndOld
      dockerfile: Dockerfile
    container_name: murcy_api_old
    ports:
      - "9090:8080"
    env_file:
      - enviroment.env
    depends_on:
      - postgres
      - mail
  murcy_app_old:
    build: 
      context: ./FrontEndOld
      dockerfile: Dockerfile
    container_name: murcy_application_old
    ports:
      - "9000:80"
    depends_on:
      - murcy_api_old
  murcy_api:
    build: 
      context: ./BackEnd
      dockerfile: Dockerfile
    container_name: murcy_api
    ports:
      - "8090:8080"
    env_file:
      - enviroment_tfg.env
    depends_on:
      - postgres
      - mail
  mail:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: murcy.es
    container_name: mail
    ports:
      - "25:25"
      - "587:587"
      - "465:465"
    volumes:
      - ./mail_data/mail:/var/mail
      - ./mail_data/state:/var/mail-state
      - ./mail_data/log:/var/log/mail
      - ./config/:/tmp/docker-mailserver/
    env_file:
      - enviroment.env
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
